<?php
$news = $this->getNewsCollection();
?>

<?php foreach ($news as $item): ?>
    <h1 align="center">
        <?php echo $item->getTitle() . '<br>'; ?>
    </h1>
    <?php $getImageName = explode("/", $item->getImage()) ?>
    <img align="left"  width="120px" src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_MEDIA).'/'. 'tsg_trial/'. $getImageName[2] ?> ">
    <p><?php echo $item->getContent(); ?></p>
<?php endforeach; ?>